name: 部署到百度云服务器 #action名称
on: [push] #在推送的时候运行此action

jobs:
  deploy_job:
    runs-on: ubuntu-latest  #运行环境
    name: build
    steps:
      # check out the repository
      - uses: actions/checkout@v3 #这里使用了github官方提供的action,checkout项目到虚拟机上
      - uses: pnpm/action-setup@v2
        with:
          version: 7    
      - name: Install Dependencies
        run: pnpm i
      - name: Build
        run: pnpm build

      # 利用action把build好的文件上传到服务器/home/StudyBlog路径下,需要确认此目录已在服务端创建
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:  
          username: 'root'   #ssh user name
          server: '${{ secrets.SERVER_IP }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} #引用之前创建好的secret
          local_path: './docs/.vitepress/dist/*'  # 对应我们项目build的文件夹路径
          remote_path: '/home/StudyBlog'